name: mmoPet
main: mmo.Pet.MMOPet
version: 0.4
website: http://forums.bukkit.org/threads/33291/
author: Rycochet <rycochet@rycochet.com>
depend: [Spout,mmoCore]

description: Display pet names above them.
